# Generated by Django 5.0.2 on 2024-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Qtde", models.CharField(max_length=30)),
                ("Codigo", models.CharField(max_length=30)),
                ("Descricao", models.CharField(max_length=100)),
                ("Unitario", models.CharField(max_length=30)),
                ("Total", models.CharField(max_length=30)),
            ],
        ),
    ]
