# Generated by Django 5.0.1 on 2024-03-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="Qtde",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="estoque",
            name="Total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="estoque",
            name="Unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
